### PR TITLE
Finally! There we go. Basic install splited from readme.md stuff

### PR DESCRIPTION
**Pull request by cpicanco**
System is case sensitive. Renaming for the original name as in:

> [Desktop Entry]
> ...
> Name=Bunsen1-dark
> ...

### CODE REVIEW

**Comment by cpicanco** [comment]
You can check the branch readme.md for the splited commits (68ae1c14db93ca1e419d0dc4a45a7c291a143f4c).

**Comment by 2ion** [comment]
Looks good! Sorry if I am nitpicking: Is it really necessary for the GNOMEy stuff to work to set the MetacityTheme key? Technically, we don't provide a 'metacity-1' folder + theme files. After reading [this](https://people.gnome.org/~shaunm/admin-guide/themes-17.html),
```
 MetacityTheme - Corresponds to the window frame setting in the Theme preference tool. Specifies which window frame setting option to apply to windows.
```
, I don't think we should set this. If this is not a hack/there is no benefit: Could you change the line to just <code>MetacityTheme=</code> again?

**Comment by cpicanco** [comment]
There is nothing to sorry dude! You are in charge here hehehehhe

So, I need read the docs and test it.

**Comment by cpicanco** [comment]
Indeed, this line seems to be mistake. May I ask you something?

This theme shows up in two configuration settings:

-This one (Customize looking and feel) controls colors, button, icons, etc.
> Start  Menu -> Settings -> User Interface Settings -> Widgets Tab

- This one (Open Box Configuration Manager) controls windows frames
> Start  Menu -> Settings -> Open Box -> Gui Config Tool -> Theme

There are more?

**Comment by hhhorb** [comment]
The widgets one is GTK2/GTK3, Openbox has it's own configuration app for the WM theme. I forget what all is in this theme, but if there's an xfwm4 theme in there, that has it's own configuration program as well. Finally, xfce4-notifyd also has it's own configuration program named, appropriately enough, xfce4-notifyd-config. :^D

**Pull request merged**
