### PR TITLE
Basic Install

### PR DESCRIPTION
**Pull request by cpicanco**
The system is case sensitive, new values based on original name:
```script
 [Desktop Entry]
...
Name=Bunsen1-dark
...
```

### CODE REVIEW

**Comment by cpicanco** [comment]
Add a proper README.md

**Comment by 2ion** [comment]
@cpicanco Thanks for the submission. I like the changes to the index.theme file; and it is true that @hhhorb gave this an uppercased name. 

As for the README, we've already [decided](http://crunchbang.org/forums/viewtopic.php?pid=420011#p420011) that we want to keep it in plaintext since it goes into /usr/share/doc. Similarly, since this is a package and not an exposé, I don't think we need install steps or screenshots in the README. Theme presentation can go into the wiki or on the gh-pages branch (@BunsenLabs/artwork-team: RFC, please) and is currently happening on the forums anyways.

If you split out the changes to the index.theme and debian/install to a separate branch, I'll merge them early.

**Comment by Unia** [comment]
While I'm not in the artwork-team, I completely agree with everything you said @2ion.

**Comment by cpicanco** [comment]
Hey guys, fell free to reject this request. I need to learn how to split out this pull request in the first place! Well, about the readme, is not a good idea create a README.md? I think understand the plain text minimalistic sake.

**Comment by hhhorb** [comment]
No, not for minimilism. Read the link to the #! forums twoion posted. It's because .md is for a specific kind of README.

**Pull request closed without merging**
